language: cpp
compiler: gcc

stages:
  - install
  - test

addons:
  apt:
    update: true
    packages:
      - gcc
      - cmake
      - build-essential
      - libbz2-dev

jobs:
  include:
    - stage: install
      script:
        - mkdir build && cd build
        - cmake ..
        - sudo make install

    - stage: test
      script:
        - cd test
        - g++ -std=c++11 -c main.cpp test*.cpp
        - g++ -std=c++11 main.o test*.o -o run-all-tests
        - ./run-all-tests
