language: cpp
compiler: gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -q gcc
  - sudo apt-get install -y cmake build-essential libbz2-dev

script:
  - mkdir build && cd build
  - cmake ..
  - sudo make install