language: cpp
compiler: gcc

addons:
  apt:
    update: true
    packages:
      - gcc
      - cmake
      - build-essential
      - libbz2-dev

script:
  - mkdir build && cd build
  - cmake ..
  - sudo make install